### ISSUE TITLE
RfC: Moving https://diyhrt.cafe to a better software.

### ISSUE THREAD

**Issue by IShouldTestMyCode** [IShouldTestMyCode/hrt-cafe-archive#13]
Hello! As you may (or may not) know, I operate the website [https://diyhrt.cafe](https://diyhrt.cafe). This website is dedicated to provide resources to those who need to do Trans DIY.

Since 2022-10-25 (Creation), the website have seen over 100K requests and thousands of visitors.

On 2022-10-23, when I noticed (Through r/diyhrt) that the now-defunct website [hrt.cafe](https://hrt.cafe) was taken down, I decided to archive the content by scraping the server. Never expecting that this would be something people actually would use/visit, and not simply doing the "I know a guy who know a guy".

Now, with such high levels of traffic, I am more motivated than ever to provide the best, most up-to-date information to the community.

However, when I downloaded [hrt.cafe](https://hrt.cafe), I only received the compiled code (Bootstrap), making it difficult for both me and the community to edit. Therefore, I propose moving [diyhrt.cafe](https://diyhrt.cafe) to a better framework/software.

The current softwares I am looking at are Wiki.js [(Example)](https://docs.requarks.io) and MediaWiki [(Example)](https://wikipedia.org).

I have added the pros and cons of switching to the table below:

|Pros to moving|Cons to moving|
|:-|:-|
|Easier to edit|Loses the look and feel of the site|
|Easier to keep up-to-date|Might be a bit harder on my server (But I can manage that)|
|Everyone, including those who do not know HTML can edit|More downtime, but I can remedy that as well by using two servers.|
|Can contain more information such as guides and a more expansive link directory||

Let me know what you think in the comments below (Or go on reddit [here!](https://www.reddit.com/user/tpyourself/comments/yjfuw6/rfc_moving_httpsdiyhrtcafe_to_a_better_software/ )!)

**Comment by princessmortix** [comment]
Look for Jekyll too! It have an integration with GitHub pages and you'll only need to write markdown.

You can see an exemple at [my school notes website](https://estudos.princessmortix.link) ([source repo](https://github.com/princessmortix/estudos-do-quarto)). It's built using Jekyll and moonwalk theme.

**Comment by CyberTailor** [comment]
Wiki is kinda overkill, I'd use a static site generator (like Sphinx).

**Comment by vexx32** [comment]
A static site that can be edited by submitting PRs to Github might be a good call actually... while a wiki is pretty robust, it's also somewhat susceptible to vandalism. Whereas from Github you can have a handful of community members vetting and approving pull requests to update a static site. 🤔 

Wiki is a nice idea though, and maybe more robust long term, as it's not down to one person or a small group of folks approving changes. Dunno.

**Comment by IShouldTestMyCode** [comment]
I'm running a trial for the wiki version for three days, and let's see how it goes!

**Comment by amydevs** [comment]
> Wiki is kinda overkill, I'd use a static site generator (like Sphinx).

i agree, in my opinion though, i think serializing all the data on the site to json might be a good idea before deciding a frontend

**Comment by Mar0xy** [comment]
I would also recommend serializing all data to json and then using an SSG for the frontend as you could pull in the data from the json files which would make editing easier. Though, I will throw in another SSG and that is Hugo which can also be used on [GitHub Pages](https://gohugo.io/hosting-and-deployment/hosting-on-github/)

**Comment by IShouldTestMyCode** [comment]
Did it ~
