### ISSUE TITLE
EUAibolit new domain

### ISSUE THREAD

**Issue by qunYp3dZSyLjoEoEg** [IShouldTestMyCode/hrt-cafe-archive#19]
**Describe the problem**
EUAibolit have changed their domain, their new address seems to be https://euaibolit.de/ instead of .com

**Location of problem**
[Copy and paste the URL/URI here!](https://www.reddit.com/r/TransDIY/comments/ys7tik/euaibolit_update/)

**Expected behaviour**
It should connect me to EUAibolit, but due to an outdated domain on the website it doesn't

**Comment by IShouldTestMyCode** [comment]
Managed on new site. Old site is extremely difficult to update. 

The new site is at https://new2.diyhrt.cafe
